version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
    networks:
      - local
  config:
    image: borosboyo/config:1.0-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/user/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - local
  discovery:
    image: borosboyo/discovery:1.0-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  gateway:
    image: borosboyo/gateway:1.0-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config
      - discovery
      - zipkin
    networks:
      - local
  email:
    image: borosboyo/email:1.0-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      gateway:
        condition: service_started
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  share:
    image: borosboyo/share:1.0-SNAPSHOT
    ports:
      - "8082:8082"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      gateway:
        condition: service_started
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  subscription:
    image: borosboyo/subscription:1.0-SNAPSHOT
    ports:
      - "8083:8083"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      gateway:
        condition: service_started
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  transform:
    image: borosboyo/transform:1.0-SNAPSHOT
    ports:
      - "8084:8084"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      gateway:
        condition: service_started
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  user:
    image: borosboyo/user:1.0-SNAPSHOT
    ports:
      - "8085:8085"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      gateway:
        condition: service_started
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - local
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - local
    depends_on:
      - postgres
  frontend:
    image: borosboyo/frontend:1.0-SNAPSHOT
    ports:
      - "5173:5173"
    container_name: frontend
    networks:
      - local

networks:
  local:
    driver: bridge