version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  config:
    image: borosboyo/config:1.0-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/user/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
  discovery:
    image: borosboyo/discovery:1.0-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
  email:
    image: borosboyo/email:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  share:
    image: borosboyo/share:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  subscription:
    image: borosboyo/subscription:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  transform:
    image: borosboyo/transform:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  user:
    image: borosboyo/user:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway:
    image: borosboyo/gateway:1.0-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config
      - discovery
      - zipkin
      - user
      - email
      - share
      - subscription
      - transform
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
        - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
        - postgres
# frontend:
#   image: borosboyo/frontend
#   ports:
#     - "5173:5173"
#   container_name: fronten