version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  config:
    image: movesong/config:1.0-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/employee/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
  discovery:
    image: movesong/discovery:1.0-SNAPSHOT
    ports:
      - "8061:8061"
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
  employee:
    image: movesong/employee:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  department:
    image: movesong/department:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - employee
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  organization:
    image: movesong/organization:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery:
        condition: service_healthy
    links:
      - config
      - discovery
      - employee
      - department
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway:
    image: movesong/gateway:1.0-SNAPSHOT
    ports:
      - "8060:8060"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config
      - discovery
      - employee
      - department
      - organization
      - zipkin
  frontend:
    image: movesong/frontend
    ports:
      - "5173:5173"
    container_name: frontend