server:
  port: 8061

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    hu.bme.aut.config: INFO
  file:
    path: ./src/main/resources/logs/
    name: ${logging.file.path}config.log