spring:
  config:
    import: "optional:configserver:http://config:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8088"

movesong:
  jwtSecret: ${MOVESONG_JWT_SECRET}