spring:
  config:
    import: "optional:configserver:http://config:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: employee
  config:
    import: "optional:configserver:http://localhost:8088"